### ISSUE TITLE
Flink does not show the output run time in stdout (see: #1)

### ISSUE THREAD

**Issue by BenjaminSchiller** [BenjaminSchiller/FlinkWrapper#2]
currently, no runtime is output (on stdout)
would be nice to split into io & computation

**Comment by BenjaminSchiller** [comment]
nice to measure:
- io
- computation
- setup

**Comment by TjWallas** [comment]
@BenjaminSchiller According to `https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/api/common/JobExecutionResult.html`, there are no other metrics that we can collect from the job manager regarding a certain job.

**Comment by TjWallas** [comment]
@BenjaminSchiller  It is also not trivial to just print the time inside the source code as the same JAR is executed by multiple executors in parallel. Hence, the only way to compute time is to account for it perhaps via a distributed accumulator as a part of the map reduce workflow itself (which is abstracted away by the gelly API for reading a graph).

**Comment by BenjaminSchiller** [comment]
hmm, ok, so not really a straight-forward way to measure the runtimes except for wall-clock time surrounding everything?

**Comment by TjWallas** [comment]
@BenjaminSchiller I guess, yes. I am currently trying to reproduce this behavior where the execution time is not being printed but, I cannot seem to get this behavior on my local VM.

**Comment by TjWallas** [comment]
@BenjaminSchiller As a result of the above commit, the job execution time will now be simply written to a file in the current working directory named `last-job-execution-time.txt`. Simple workaround that works in the context of our "single machine" setup.

**Comment by BenjaminSchiller** [comment]
@TjWallas
this appears not to be working correctly.....
even if a directory path is specified for the output (e.g., output/test/) the output is written to a single file (e.g., output/test).
where should this file be?
did you test this?

**Comment by TjWallas** [comment]
@BenjaminSchiller I did in fact test this locally. The file is created in the current working directory. Not, in the output path. So for example if you are inside `/home/something`, the file would be inside that location.

Could you please `mvn clean install` and try again?

**Comment by BenjaminSchiller** [comment]
@TjWallas 
i did that already, tried it again but does not work....

**Comment by TjWallas** [comment]
@BenjaminSchiller Please close this issue when you confirm that the error no longer happens on the p2pram machine :)
